version: '2.1'
services:
  jekyll:
    build:
      context: "./"
      dockerfile: "Dockerfile"
    volumes:
      - ./:/usr/src/app
    network_mode: "host"
    environment:
      - JEKYLL_ENV=development
    command: liveserve --force_polling --host 192.168.50.4
