#!/bin/bash

set -e

if [[ -n "${ODV_DEBUG}" ]]; then
    set -x
fi

function usage() {
    echo -n \
         "Usage: $(basename "$0") 
Setup the development environment.
"
}

if [ "${BASH_SOURCE[0]}" = "${0}" ]; then
    if [ "${1:-}" = "--help" ]; then
        usage
    else
        vagrant up --provision
        rm -rf deployment/ansible/roles/azavea.*
    fi
fi
